### ISSUE TITLE
Runing the demo.py

### ISSUE THREAD

**Issue by soumboussaha** [openwpm/OpenWPM#1050]
when running the demo.py script I come across this error, I am running the script form inside the docker container as follows :

`sudo docker run openwpm python demo.py`

```
browser_manager      - INFO     - BROWSER 2034838209: Launching browser...
browser_manager      - ERROR    - BROWSER 2034838209: Crash in driver, restarting browser manager
Traceback (most recent call last):
  File "/opt/OpenWPM/openwpm/browser_manager.py", line 716, in run
    driver, browser_profile_path, display = deploy_firefox.deploy_firefox(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/OpenWPM/openwpm/deploy_browsers/deploy_firefox.py", line 147, in deploy_firefox
    driver = webdriver.Firefox(
             ^^^^^^^^^^^^^^^^^^
  File "/opt/mamba/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/opt/mamba/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/opt/mamba/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mamba/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/opt/mamba/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

browser_manager      - ERROR    - BROWSER 2034838209: Spawn unsuccessful  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
browser_manager      - ERROR    - BROWSER 2034838209: Crash in driver, restarting browser manager
```

**Comment by vringar** [comment]
Hey,
by default OpenWPM tries to use the native display server, so I can't run in a docker container
See [these instructions](https://github.com/openwpm/OpenWPM#running-measurements-from-inside-the-container) for how to do that.

However in the latest version of OpenWPM (which has not yet been tagged), so it can only be access via `docker pull openwpm/openwpm:latest`) you can also run `docker run openwpm python demo.py --headless`
