### ISSUE TITLE
openwpm.errors.BrowserConfigError: The extension did not boot up in time

### ISSUE THREAD

**Issue by sober1998** [openwpm/OpenWPM#997]
Hi, I'm run demo.py, and I got the following error.
```
ubuntu@VM-0-9-ubuntu:~/OpenWPM$ python demo.py
browser_manager      - INFO     - BROWSER 255079965: Launching browser...
browser_manager      - ERROR    - BROWSER 255079965: Failed to complete extension startup in time
browser_manager      - ERROR    - BROWSER 255079965: BrowserConfigError thrown, informing parent and raising
storage_controller   - INFO     - Terminating handler, because the underlying socket closed
storage_controller   - INFO     - Received shutdown signal!
Traceback (most recent call last):
  File "/home/ubuntu/OpenWPM/demo.py", line 54, in <module>
    with TaskManager(
  File "/home/ubuntu/OpenWPM/openwpm/task_manager.py", line 123, in __init__
    self._launch_browsers()
  File "/home/ubuntu/OpenWPM/openwpm/task_manager.py", line 184, in _launch_browsers
    success = browser.launch_browser_manager()
  File "/home/ubuntu/OpenWPM/openwpm/browser_manager.py", line 185, in launch_browser_manager
    ready = check_queue(launch_status)
  File "/home/ubuntu/OpenWPM/openwpm/browser_manager.py", line 148, in check_queue
    raise exc.with_traceback(tb)
  File "/home/ubuntu/OpenWPM/openwpm/browser_manager.py", line 726, in run
    extension_socket = self._start_extension(browser_profile_path)
  File "/home/ubuntu/OpenWPM/openwpm/browser_manager.py", line 706, in _start_extension
    raise BrowserConfigError("The extension did not boot up in time")
openwpm.errors.BrowserConfigError: The extension did not boot up in time
```
Actually, this error happens occasionally, my machine is a tencent cloud server with 8-core 16GB, and OS is Ubuntu 18.04. I only modified a little in demo.py, config.py and fingerprint.json. 
Would you mind taking a look at this issue? Thank you in advance.

**Comment by vringar** [comment]
For future reference:
If an error like this occurs, you should first look into the openwpm.log to see if anything is there.
Secondly, reporting an error without mentioning the version you are using makes it hard to debug.
